config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  ActiveAdmin.routes(self)

  resources :authors
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy

  validates :name, presence: true, length: { in: 2..200 }
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author

  validates :author_id, presence: true
  validates :title, presence: true, length: { in: 2..200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author!, only: %i[show edit update destroy]

  def index
    @authors = Author.all
  end

  def show; end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to @author
    else
      render :new
    end
  end

  def edit; end

  def update
    if @author.update(author_params)
      redirect_to @author
    else
      render :edit
    end
  end

  def destroy
    @author.destroy
    redirect_to authors_path
  end

  private

  def set_author!
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book!, only: %i[show edit update destroy]
  before_action :set_authors, only: %i[new create]

  def index
    @books = Book.includes(:author)
  end

  def show; end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book
    else
      render :new
    end
  end

  def edit; end

  def update
    if @book.update(book_params)
      redirect_to @book
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def set_book!
    @book = Book.find(params[:id])
  end

  def set_authors
    @authors = Author.all
  end

  def book_params
    params.require(:book).permit(:author_id, :title, :genre, :shelf)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_form.html.erb
<%= simple_form_for @author do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/authors/edit.html.erb
<h1>Edit Author</h1>

<%= render 'form' %>

app/views/authors/index.html.erb
<%= link_to 'New Author', new_author_path %>

<table>
  <caption>Authors</caption>
  <tr>
    <th>Name</th>
    <th>Settings</th>
  </tr>
  <% @authors.each do |author| %>
    <tr>
      <td><%= link_to author.name, author_path(author) %></td>
      <td>
        <%= link_to 'Edit', edit_author_path(author) %>
        <%= link_to 'Delete', author_path(author), method: :delete %>
      </td>
    </tr>
  <% end %>
</table>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

app/views/authors/show.html.erb
<table>
  <caption><%= @author.name %> - Books</caption>
  <tr>
    <th>Book name</th>
  </tr>
  <% @author.books.each do |book| %>
    <tr>
      <td>
        <%= link_to book.title, book_path(book) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
  <%= f.input :author_id, collection: @authors %>
  <%= f.input :title %>
  <%= f.input :genre %>
  <%= f.input :shelf %>
  <%= f.button :submit %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render 'form' %>

app/views/books/index.html.erb
<%= link_to 'New Book', new_book_path %>

<table>
  <caption>Books</caption>
  <tr>
    <th>Name</th>
    <th>№ shelf</th>
    <th>Genre</th>
    <th>Author</th>
    <th>Settings</th>
  </tr>
  <% @books.each do |book| %>
    <tr>
      <td><%= link_to book.title, book_path(book) %></td>
      <td><%= book.shelf %></td>
      <td><%= book.genre %></td>
      <td><%= book.author.name %></td>
      <td>
        <%= link_to 'Edit', edit_book_path(book) %>
        <%= link_to 'Delete', book_path(book), method: :delete %>
      </td>
    </tr>
  <% end %>
</table>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<table>
  <caption>Book</caption>
  <tr>
    <th>Name</th>
    <th>№ shelf</th>
    <th>Genre</th>
    <th>Author</th>
    <th>Settings</th>
  </tr>
  <tr>
    <td><%= @book.title %></td>
    <td><%= @book.shelf %></td>
    <td><%= @book.genre %></td>
    <td><%= @book.author.name %></td>
    <td>
      <%= link_to 'Edit', edit_book_path(@book) %>
      <%= link_to 'Delete', book_path(@book), method: :delete %>
    </td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OneStoryPointDomanetskii</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
  </head>

  <body>
    <%= tag.header render 'shared/navbar' %>

    <%= tag.main yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav>
  <div>
    <ul>
      <li><%= link_to 'All authors', authors_path %></li>
      <li><%= link_to 'All books', books_path %></li>
    </ul>
  </div>
</nav>